# -*- coding: utf-8 -*-
"""prompt-to-prompt_ldm_self.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iuwjqWn9GubM0Zob4oM9PMXlhneUVndg

## Copyright 2022 Google LLC. Double-click for license information.
"""

from google.colab import drive
drive.mount('/content/drive')

# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

!sudo apt-get install python3.9
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
!sudo update-alternatives --config python3

!python --version

!sudo apt-get update
!sudo apt-get install -y python3.9-distutils
!curl -O https://bootstrap.pypa.io/get-pip.py
!python3.9 get-pip.py

"""## Prompt-to-Prompt with Latent Diffusion"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/GenAI_final/GenAI-soft-prompt-to-prompt

!pip install -r requirements.txt

"""## Imports, constants, loading model"""

from typing import Union, Tuple, List, Callable, Dict, Optional
import torch
import torch.nn.functional as nnf
from diffusers import DiffusionPipeline
import numpy as np
from IPython.display import display
from PIL import Image
import abc
import ptp_utils
import seq_aligner

import importlib
importlib.reload(ptp_utils)

device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu')
model_id = "CompVis/ldm-text2im-large-256"
NUM_DIFFUSION_STEPS = 50
GUIDANCE_SCALE = 5.
MAX_NUM_WORDS = 77
# load model and scheduler
ldm = DiffusionPipeline.from_pretrained(model_id).to(device)
tokenizer = ldm.tokenizer

"""## Prompt-to-Prompt Attnetion Controllers
Our main logic is implemented in the `forward` call in an `AttentionControl` object.
The forward is called in each attention layer of the diffusion model and it can modify the input attnetion weights `attn`.

`is_cross`, `place_in_unet in ("down", "mid", "up")`, `AttentionControl.cur_step` can help us track the exact attention layer and timestamp during the diffusion iference.

"""

class LocalBlend:

    def __call__(self, x_t, attention_store, step):
        k = 1
        maps = attention_store["down_cross"][:2] + attention_store["up_cross"][3:6]
        maps = [item.reshape(self.alpha_layers.shape[0], -1, 1, 16, 16, MAX_NUM_WORDS) for item in maps]
        maps = torch.cat(maps, dim=1)
        maps = (maps * self.alpha_layers).sum(-1).mean(1)
        mask = nnf.max_pool2d(maps, (k * 2 + 1, k * 2 +1), (1, 1), padding=(k, k))
        mask = nnf.interpolate(maps, size=(x_t.shape[2:]))
        mask = mask / mask.max(2, keepdims=True)[0].max(3, keepdims=True)[0]
        mask = mask.gt(self.threshold)
        mask = (mask[:1] + mask).float()
        x_t = x_t[:1] + mask * (x_t - x_t[:1])
        return x_t

    def __init__(self, prompts: List[str], words: [List[List[str]]], threshold: float = .3):
        alpha_layers = torch.zeros(len(prompts),  1, 1, 1, 1, MAX_NUM_WORDS)
        for i, (prompt, words_) in enumerate(zip(prompts, words)):
            if type(words_) is str:
                words_ = [words_]
            for word in words_:
                ind = ptp_utils.get_word_inds(prompt, word, tokenizer)
                alpha_layers[i, :, :, :, :, ind] = 1
        self.alpha_layers = alpha_layers.to(device)
        self.threshold = threshold


class AttentionControl(abc.ABC):

    def step_callback(self, x_t):
        return x_t

    def between_steps(self):
        return

    @abc.abstractmethod
    def forward (self, attn, is_cross: bool, place_in_unet: str):
        raise NotImplementedError

    def __call__(self, attn, is_cross: bool, place_in_unet: str):
        h = attn.shape[0]
        attn[h // 2:] = self.forward(attn[h // 2:], is_cross, place_in_unet)
        self.cur_att_layer += 1
        if self.cur_att_layer == self.num_att_layers:
            self.cur_att_layer = 0
            self.cur_step += 1
            self.between_steps()
        return attn

    def reset(self):
        self.cur_step = 0
        self.cur_att_layer = 0

    def __init__(self):
        self.cur_step = 0
        self.num_att_layers = -1
        self.cur_att_layer = 0


class EmptyControl(AttentionControl):

    def forward (self, attn, is_cross: bool, place_in_unet: str):
        return attn


class AttentionStore(AttentionControl):

    @staticmethod
    def get_empty_store():
        return {"down_cross": [], "mid_cross": [], "up_cross": [],
                "down_self": [],  "mid_self": [],  "up_self": []}

    def forward(self, attn, is_cross: bool, place_in_unet: str):
        if attn.shape[1] <= 16 ** 2:  # avoid memory overhead
            key = f"{place_in_unet}_{'cross' if is_cross else 'self'}"
            self.step_store[key].append(attn)
        return attn

    def between_steps(self):
        if len(self.attention_store) == 0:
            self.attention_store = self.step_store
        else:
            for key in self.attention_store:
                for i in range(len(self.attention_store[key])):
                    self.attention_store[key][i] += self.step_store[key][i]
        self.step_store = self.get_empty_store()

    def get_average_attention(self):
        average_attention = {key: [item / self.cur_step for item in self.attention_store[key]] for key in self.attention_store}
        return average_attention


    def reset(self):
        super(AttentionStore, self).reset()
        self.step_store = self.get_empty_store()
        self.attention_store = {}

    def __init__(self):
        super(AttentionStore, self).__init__()
        self.step_store = self.get_empty_store()
        self.attention_store = {}


class AttentionControlEdit(AttentionStore, abc.ABC):

    def step_callback(self, x_t):
        if self.local_blend is not None:
            x_t = self.local_blend(x_t, self.attention_store, self.cur_step)
        return x_t

    def replace_self_attention(self, attn_base, att_replace):
        if att_replace.shape[2] <= 16 ** 2:
            return attn_base.unsqueeze(0).expand(att_replace.shape[0], *attn_base.shape)
        else:
            return att_replace

    @abc.abstractmethod
    def replace_cross_attention(self, attn_base, att_replace):
        raise NotImplementedError

    def forward(self, attn, is_cross: bool, place_in_unet: str):
        super(AttentionControlEdit, self).forward(attn, is_cross, place_in_unet)
        if is_cross or (self.num_self_replace[0] <= self.cur_step < self.num_self_replace[1]):
            h = attn.shape[0] // (self.batch_size)
            attn = attn.reshape(self.batch_size, h, *attn.shape[1:])
            attn_base, attn_repalce = attn[0], attn[1:]
            if is_cross:
                alpha_words = self.cross_replace_alpha[self.cur_step]
                attn_repalce_new = self.replace_cross_attention(attn_base, attn_repalce) * alpha_words + (1 - alpha_words) * attn_repalce
                attn[1:] = attn_repalce_new
            else:
                # --- NEW: soft self-attention mixing ---
                base_self = self.replace_self_attention(attn_base, attn_repalce)

                if getattr(self, "self_timestep_scaler", None) is not None:
                    alpha_self = self.self_timestep_scaler[self.cur_step]  # scalar in [0, 1]
                else:
                    alpha_self = 1.0  # fallback: original "full base" behavior

                # alpha_self: weight on base; (1 - alpha_self): weight on edited
                attn[1:] = alpha_self * base_self + (1.0 - alpha_self) * attn_repalce

            attn = attn.reshape(self.batch_size * h, *attn.shape[2:])
            return attn

    def __init__(self, prompts, num_steps: int,
                 cross_replace_steps: Union[float, Tuple[float, float], Dict[str, Tuple[float, float]]],
                 self_replace_steps: Union[float, Tuple[float, float]],
                 local_blend: Optional[LocalBlend],
                 time_step_scaler=None
                 ):
        super(AttentionControlEdit, self).__init__()
        self.batch_size = len(prompts)
        # Do NOT pass time_step_scaler here -> original P2P schedule
        self.cross_replace_alpha = ptp_utils.get_time_words_attention_alpha(
            prompts,
            num_steps,
            cross_replace_steps,
            tokenizer
        ).to(device)
        if type(self_replace_steps) is float:
            self_replace_steps = 0, self_replace_steps
        self.num_self_replace = int(num_steps * self_replace_steps[0]), int(num_steps * self_replace_steps[1])
        self.local_blend = local_blend
        # NEW: scalar schedule for self-attention mixing (base vs edited)
        self.self_timestep_scaler = ptp_utils._build_timestep_scaler(num_steps, time_step_scaler)
        if self.self_timestep_scaler is not None:
            self.self_timestep_scaler = self.self_timestep_scaler.view(num_steps + 1).to(device)

class AttentionReplace(AttentionControlEdit):

    def replace_cross_attention(self, attn_base, att_replace):
        return torch.einsum('hpw,bwn->bhpn', attn_base, self.mapper)

    def __init__(self, prompts, num_steps: int, cross_replace_steps: float, self_replace_steps: float,
                 local_blend: Optional[LocalBlend] = None,
                 time_step_scaler=None):
        super(AttentionReplace, self).__init__(
            prompts, num_steps, cross_replace_steps, self_replace_steps, local_blend,
            time_step_scaler=time_step_scaler
        )
        self.mapper = seq_aligner.get_replacement_mapper(prompts, tokenizer).to(device)


class AttentionRefine(AttentionControlEdit):

    def replace_cross_attention(self, attn_base, att_replace):
        attn_base_replace = attn_base[:, :, self.mapper].permute(2, 0, 1, 3)
        attn_replace = attn_base_replace * self.alphas + att_replace * (1 - self.alphas)
        return attn_replace

    def __init__(self, prompts, num_steps: int, cross_replace_steps: float, self_replace_steps: float,
                 local_blend: Optional[LocalBlend] = None,
                 time_step_scaler=None):
        super(AttentionRefine, self).__init__(
            prompts, num_steps, cross_replace_steps, self_replace_steps, local_blend,
            time_step_scaler=time_step_scaler
        )
        self.mapper, alphas = seq_aligner.get_refinement_mapper(prompts, tokenizer)
        self.mapper, alphas = self.mapper.to(device), alphas.to(device)
        self.alphas = alphas.reshape(alphas.shape[0], 1, 1, alphas.shape[1])


class AttentionReweight(AttentionControlEdit):

    def replace_cross_attention(self, attn_base, att_replace):
        if self.prev_controller is not None:
            attn_base = self.prev_controller.replace_cross_attention(attn_base, att_replace)
        attn_replace = attn_base[None, :, :, :] * self.equalizer[:, None, None, :]
        return attn_replace

    def __init__(self, prompts, num_steps: int, cross_replace_steps: float, self_replace_steps: float, equalizer,
                local_blend: Optional[LocalBlend] = None,
                controller: Optional[AttentionControlEdit] = None,
                time_step_scaler=None):
        super(AttentionReweight, self).__init__(
            prompts, num_steps, cross_replace_steps, self_replace_steps, local_blend,
            time_step_scaler=time_step_scaler
        )
        self.equalizer = equalizer.to(device)
        self.prev_controller = controller


def get_equalizer(text: str, word_select: Union[int, Tuple[int, ...]], values: Union[List[float],
                  Tuple[float, ...]]):
    if type(word_select) is int or type(word_select) is str:
        word_select = (word_select,)
    equalizer = torch.ones(len(values), 77)
    values = torch.tensor(values, dtype=torch.float32)
    for word in word_select:
        inds = ptp_utils.get_word_inds(text, word, tokenizer)
        for i in inds:
            equalizer[:, i] = values
    return equalizer

def aggregate_attention(attention_store: AttentionStore, res: int, from_where: List[str], is_cross: bool, select: int):
    out = []
    attention_maps = attention_store.get_average_attention()
    num_pixels = res ** 2
    for location in from_where:
        for item in attention_maps[f"{location}_{'cross' if is_cross else 'self'}"]:
            if item.shape[1] == num_pixels:
                cross_maps = item.reshape(len(prompts), -1, res, res, item.shape[-1])[select]
                out.append(cross_maps)
    out = torch.cat(out, dim=0)
    out = out.sum(0) / out.shape[0]
    return out.cpu()


def show_cross_attention(attention_store: AttentionStore, res: int, from_where: List[str], select: int = 0):
    tokens = tokenizer.encode(prompts[select])
    decoder = tokenizer.decode
    attention_maps = aggregate_attention(attention_store, res, from_where, True, select)
    images = []
    for i in range(len(tokens)):
        image = attention_maps[:, :, i]
        image = 255 * image / image.max()
        image = image.unsqueeze(-1).expand(*image.shape, 3)
        image = image.numpy().astype(np.uint8)
        image = np.array(Image.fromarray(image).resize((256, 256)))
        image = ptp_utils.text_under_image(image, decoder(int(tokens[i])))
        images.append(image)
    ptp_utils.view_images(np.stack(images, axis=0))


def show_self_attention_comp(attention_store: AttentionStore, res: int, from_where: List[str],
                        max_com=10, select: int = 0):
    attention_maps = aggregate_attention(attention_store, res, from_where, False, select).numpy().reshape((res ** 2, res ** 2))
    u, s, vh = np.linalg.svd(attention_maps - np.mean(attention_maps, axis=1, keepdims=True))
    images = []
    for i in range(max_com):
        image = vh[i].reshape(res, res)
        image = image - image.min()
        image = 255 * image / image.max()
        image = np.repeat(np.expand_dims(image, axis=2), 3, axis=2).astype(np.uint8)
        image = Image.fromarray(image).resize((256, 256))
        image = np.array(image)
        images.append(image)
    ptp_utils.view_images(np.concatenate(images, axis=1))

def sort_by_eq(eq):

    def inner_(images):
        swap = 0
        if eq[-1] < 1:
            for i in range(len(eq)):
                if eq[i] > 1 and eq[i + 1] < 1:
                    swap = i + 2
                    break
        else:
             for i in range(len(eq)):
                if eq[i] < 1 and eq[i + 1] > 1:
                    swap = i + 2
                    break
        print(swap)
        if swap > 0:
            images = np.concatenate([images[1:swap], images[:1], images[swap:]], axis=0)

        return images
    return inner_


def run_and_display(prompts, controller, latent=None, run_baseline=True, callback:Optional[Callable[[np.ndarray], np.ndarray]] = None, generator=None):
    if run_baseline:
        print("w.o. prompt-to-prompt")
        images, latent = run_and_display(prompts, EmptyControl(), latent=latent, run_baseline=False)
        print("results with prompt-to-prompt")
    images, x_t = ptp_utils.text2image_ldm(ldm, prompts, controller, latent=latent, num_inference_steps=NUM_DIFFUSION_STEPS, guidance_scale=GUIDANCE_SCALE, generator=generator)
    if callback is not None:
        images = callback(images)
    ptp_utils.view_images(images)
    return images, x_t

"""## Cross-Attention Visualization"""

g_cpu = torch.Generator().manual_seed(888)
prompts = ["A painting of a bear eating an apple"]
controller = AttentionStore()
images, x_t = run_and_display(prompts, controller, run_baseline=False, generator=g_cpu)
show_cross_attention(controller, res=16, from_where=["up", "down"])

"""## Replacement edit with Prompt-to-Prompt"""

# Main Experiment - Self Attention Injection with different schedulers:
import os
import csv
import numpy as np
from PIL import Image

num_steps = NUM_DIFFUSION_STEPS

def linear_decay_scaler(t: int):
    return 1.0 - float(t) / float(num_steps)

def exp_decay_scaler(t: int, tau: float = 0.3):
    x = float(t) / float(num_steps)
    return float(np.exp(-x / tau))

def sigmoid_scaler(t: int, k: float = 10.0, mid: float = 0.5):
    x = float(t) / float(num_steps)
    return float(1.0 / (1.0 + np.exp(k * (x - mid))))

def quadratic_slow_to_fast_scaler(t: int, power: float = 2.0):
    x = float(t) / float(num_steps)
    alpha = 1.0 - (x ** power)
    return float(np.clip(alpha, 0.0, 1.0))


def generate_images_from_csv(
    csv_path: str = "prompts.csv",
    base_save_dir: str = "data/sigmoid/self",
    reuse_latent=None,
):
    """
    Read prompts from csv_path and generate images for each row.
    Saves images to data/<method>/self/<Type>/0.png ... 10.png
    """
    os.makedirs(base_save_dir, exist_ok=True)

    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        for row_idx, row in enumerate(reader):
            type_name = row["Type"]

            prompts = [
                row[f"Prompt{i}"]
                for i in range(1, 12)
                if row.get(f"Prompt{i}") is not None and row[f"Prompt{i}"].strip() != ""
            ]

            print(f"\n=== Row {row_idx} | Type = {type_name} | #prompts = {len(prompts)} ===")

            save_dir = os.path.join(base_save_dir, type_name)
            os.makedirs(save_dir, exist_ok=True)

            controller = AttentionReplace(
                prompts=prompts,
                num_steps=NUM_DIFFUSION_STEPS,
                cross_replace_steps=0.5,
                self_replace_steps=(0.0, 1.0),
                local_blend=None,
                time_step_scaler=sigmoid_scaler,
            )

            # NOTE: generator=None, latent=reuse_latent => seed
            images, _ = run_and_display(
                prompts,
                controller,
                latent=reuse_latent,
                run_baseline=True,
            )

            for i, img in enumerate(images):
                img_pil = Image.fromarray(img.astype(np.uint8))
                filename = f"{i}.png"
                out_path = os.path.join(save_dir, filename)
                img_pil.save(out_path)

            print(f"Saved {len(prompts)} images to {save_dir}")

generate_images_from_csv(
    csv_path="prompts.csv",
    base_save_dir="data/sigmoid/self",
    reuse_latent=x_t,
)

import numpy as np
import matplotlib.pyplot as plt

num_steps = 50

# Scheduler Plot

def linear_decay_scaler(t: int):
    return 1.0 - float(t) / float(num_steps)

def exp_decay_scaler(t: int, tau: float = 0.3):
    x = float(t) / float(num_steps)
    return float(np.exp(-x / tau))

def sigmoid_scaler(t: int, k: float = 10.0, mid: float = 0.5):
    x = float(t) / float(num_steps)
    return float(1.0 / (1.0 + np.exp(k * (x - mid))))

def quadratic_slow_to_fast_scaler(t: int, power: float = 2.0):
    x = float(t) / float(num_steps)
    return float(np.clip(1.0 - (x ** power), 0.0, 1.0))

def baseline_replace_scaler(t: int):
    return 1.0 if t < num_steps // 2 else 0.0



timesteps = np.arange(0, num_steps + 1)

linear_vals = np.array([linear_decay_scaler(t) for t in timesteps])
exp_vals = np.array([exp_decay_scaler(t) for t in timesteps])
sigmoid_vals = np.array([sigmoid_scaler(t) for t in timesteps])
quad_vals = np.array([quadratic_slow_to_fast_scaler(t) for t in timesteps])
baseline_vals = np.array([baseline_replace_scaler(t) for t in timesteps])


plt.figure(figsize=(8, 5))

plt.plot(timesteps, linear_vals, label="Linear", linewidth=2)
plt.plot(timesteps, exp_vals, label="Exponential", linewidth=2)
plt.plot(timesteps, sigmoid_vals, label="Sigmoid", linewidth=2)
plt.plot(timesteps, quad_vals, label="Quadratic", linewidth=2)
plt.plot(timesteps, baseline_vals, label="Baseline Replace", linewidth=3, linestyle="--")

plt.ylim(-0.05, 1.05)
plt.xlabel("Timestep")
plt.ylabel("α(t)  (Weight on Source Attention)")
plt.title("Attention Blending Schedules")
plt.grid(alpha=0.3)
plt.legend()
plt.tight_layout()
plt.show()

# Test: My experiment 1 (self attention injection with linear scheduler):
prompts = ["A painting of a bear eating an apple",
           "A painting of a cat eating an apple",
           "A painting of a dog eating an apple",
           "A painting of a lion eating an apple",
          ]

num_steps = NUM_DIFFUSION_STEPS

#Linear scheduler:
def linear_decay_scaler(t: int):
    return 1.0 - float(t) / float(num_steps)

controller = AttentionReplace(
    prompts,
    NUM_DIFFUSION_STEPS,
    cross_replace_steps=0.8, # original: 80% replace, 20% no replace
    self_replace_steps=(0.0, 1.0), # Edited: apply self-attn mixing all steps
    local_blend=None,
    time_step_scaler=linear_decay_scaler
)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)


# Visualize self-attention schedule alpha_self(t)
import matplotlib.pyplot as plt
import numpy as np

alpha_self_vals = controller.self_timestep_scaler.detach().cpu().numpy()
timesteps = np.arange(alpha_self_vals.shape[0])

plt.figure(figsize=(6, 4))
plt.plot(timesteps, alpha_self_vals, linewidth=2)
plt.xlabel("timestep")
plt.ylabel("alpha_self (weight on base self-attn)")
plt.title("Self-attention schedule: linear decay")
plt.ylim(-0.05, 1.05)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# My experiment 2 (self attention injection with exp_decay scheduler):
prompts = ["A painting of a bear eating an apple",
           "A painting of a cat eating an apple",
           "A painting of a dog eating an apple",
           "A painting of a lion eating an apple",
          ]

num_steps = NUM_DIFFUSION_STEPS

def exp_decay_scaler(t: int, tau: float = 0.3):
    """Exponential: starts near 1, decays quickly then slowly."""
    x = float(t) / float(num_steps)
    return float(np.exp(-x / tau))


controller = AttentionReplace(
    prompts,
    NUM_DIFFUSION_STEPS,
    cross_replace_steps=0.8, # original: 80% replace, 20% no replace
    self_replace_steps=(0.0, 1.0), # Edited: apply self-attn mixing all steps
    local_blend=None,
    time_step_scaler=exp_decay_scaler
)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)


# Visualize self-attention schedule alpha_self(t)
import matplotlib.pyplot as plt
import numpy as np

alpha_self_vals = controller.self_timestep_scaler.detach().cpu().numpy()
timesteps = np.arange(alpha_self_vals.shape[0])

plt.figure(figsize=(6, 4))
plt.plot(timesteps, alpha_self_vals, linewidth=2)
plt.xlabel("timestep")
plt.ylabel("alpha_self (weight on base self-attn)")
plt.title("Self-attention schedule: exp_decay")
plt.ylim(-0.05, 1.05)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# My experiment 3 (self attention injection with sigmoid scheduler):
prompts = ["A painting of a bear eating an apple",
           "A painting of a cat eating an apple",
           "A painting of a dog eating an apple",
           "A painting of a lion eating an apple",
          ]

num_steps = NUM_DIFFUSION_STEPS

def sigmoid_scaler(t: int, k: float = 10.0, mid: float = 0.5):
    x = float(t) / float(num_steps)
    return float(1.0 / (1.0 + np.exp(k * (x - mid))))

controller = AttentionReplace(
    prompts,
    NUM_DIFFUSION_STEPS,
    cross_replace_steps=0.8, # original: 80% replace, 20% no replace
    self_replace_steps=(0.0, 1.0), # Edited: apply self-attn mixing all steps
    local_blend=None,
    time_step_scaler=sigmoid_scaler
)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)


# Visualize self-attention schedule alpha_self(t)
import matplotlib.pyplot as plt
import numpy as np

alpha_self_vals = controller.self_timestep_scaler.detach().cpu().numpy()
timesteps = np.arange(alpha_self_vals.shape[0])

plt.figure(figsize=(6, 4))
plt.plot(timesteps, alpha_self_vals, linewidth=2)
plt.xlabel("timestep")
plt.ylabel("alpha_self (weight on base self-attn)")
plt.title("Self-attention schedule: sigmoid scheduler")
plt.ylim(-0.05, 1.05)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# My experiment 4 (self attention injection with quadratic_slow_to_fast_scaler scheduler):
prompts = ["A painting of a bear eating an apple",
           "A painting of a cat eating an apple",
           "A painting of a dog eating an apple",
           "A painting of a lion eating an apple",
          ]

num_steps = NUM_DIFFUSION_STEPS

def quadratic_slow_to_fast_scaler(t: int, power: float = 2.0):
    """
    Concave-down decay like the black curve:
    starts near 1, decreases slowly at first,
    then drops quickly near the end.
    """
    x = float(t) / float(num_steps)
    alpha = 1.0 - (x ** power)
    return float(np.clip(alpha, 0.0, 1.0))


controller = AttentionReplace(
    prompts,
    NUM_DIFFUSION_STEPS,
    cross_replace_steps=0.8, # original: 80% replace, 20% no replace
    self_replace_steps=(0.0, 1.0), # Edited: apply self-attn mixing all steps
    local_blend=None,
    time_step_scaler=quadratic_slow_to_fast_scaler
)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)


# Visualize self-attention schedule alpha_self(t)
import matplotlib.pyplot as plt
import numpy as np

alpha_self_vals = controller.self_timestep_scaler.detach().cpu().numpy()
timesteps = np.arange(alpha_self_vals.shape[0])

plt.figure(figsize=(6, 4))
plt.plot(timesteps, alpha_self_vals, linewidth=2)
plt.xlabel("timestep")
plt.ylabel("alpha_self (weight on base self-attn)")
plt.title("Self-attention schedule: quadratic_slow_to_fast_scaler")
plt.ylim(-0.05, 1.05)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

prompts = ["A painting of a bear eating an apple",
           "A painting of a cat eating an apple",
           "A painting of a dog eating an apple",
           "A painting of a lion eating an apple",
          ]
controller = AttentionReplace(
    prompts,
    NUM_DIFFUSION_STEPS,
    cross_replace_steps=.8,
    self_replace_steps=.2
    )
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)

"""### Modify Cross-Attention injection #steps for specific words
Next, we can reduce the restriction on our lion by reducing the number of cross-attention injection with respect to the replacement words.
"""

prompts = ["A painting of a squirrel eating a burger",
           "A painting of a lion eating a burger",
           "A painting of a cat eating a burger",
           "A painting of a deer eating a burger",
          ]
controller = AttentionReplace(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "lion": .4, "cat": .3, "deer": .2},
                              self_replace_steps=0.2)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

"""### Local Edit
Lastly, if we want to only replace the burger, we can apply a local edit with respect to to the replacement words.
"""

prompts = ["A painting of a bear eating an apple",
           "A painting of a cat eating an apple",
           "A painting of a dog eating an apple",
           "A painting of a lion eating an apple",
          ]

controller = AttentionReplace(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "cat": .2, "dog": .2, "lion": .2},
                              self_replace_steps=0.2, local_blend=None)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

prompts = ["A painting of a squirrel eating a burger",
           "A painting of a squirrel eating a lasagne",
           "A painting of a squirrel eating a pretzel",
           "A painting of a squirrel eating a sushi",
          ]

lb = LocalBlend(prompts, ("burger", "lasagne", "pretzel", "sushi"))
controller = AttentionReplace(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "lasagne": .2, "pretzel": .2, "sushi": .2},
                              self_replace_steps=0.2, local_blend=lb)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

"""## Refinement edit"""

prompts = ["A painting of a squirrel eating a burger",
           "A watercolor painting of a squirrel eating a burger",
           "A dark painting of a squirrel eating a burger",
           "A realitic photo of a squirrel eating a burger",
          ]

controller = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=.8, self_replace_steps=.2)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)

prompts = ["A river between mountains",
           "A river between mountains at autumn",
           "A river between mountains at winter",
           "A river between mountains at sunset",
          ]

controller = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=.8, self_replace_steps=.4)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)

prompts = ["A car on a bridge",
           "A muscle car on a bridge",
           "A futuristic car on a bridge",
           "A retro car on a bridge",]


lb = LocalBlend(prompts, ("car", ("muscle", "car"), ("futuristic", "car"), ("retro", "car")))
controller = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "car": .2},
                             self_replace_steps=.4, local_blend=lb)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)

"""## Attention Re-Weighting"""

prompts = ["A photo of a sunset by the sea"] * 4
equalizer = get_equalizer(prompts[0], word_select=("sunset",), values=(.5, .0, -.5))
controller = AttentionReweight(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=1., self_replace_steps=.2, equalizer=equalizer)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

prompts = ["A photo of a poppy field at night"] * 4
equalizer = get_equalizer(prompts[0], word_select=("night",), values=(.5, 0,  -.5))
controller = AttentionReweight(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=1., self_replace_steps=.2, equalizer=equalizer)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

"""### Edit Composition
It might be useful to use Attention Re-Weighting with a previous edit method.
"""

prompts = ["cake",
           "birthday cake"]


lb = LocalBlend(prompts, ("cake", ("birthday", "cake")))
controller = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=.8, self_replace_steps=.4, local_blend=lb)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

"""result with more attetnion to `"birthday"`"""

prompts = ["cake",
           "birthday cake"]


lb = LocalBlend(prompts, ("cake", ("birthday", "cake")))
controller_a = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=.8, self_replace_steps=.4, local_blend=lb)

## pay 5 times more attention to the word "birthday"
equalizer = get_equalizer(prompts[1], ("birthday"), (5,))
controller = AttentionReweight(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=.8, self_replace_steps=.4, equalizer=equalizer, local_blend=lb, controller=controller_a)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

prompts = ["A car on a bridge",
           "A cabriolet car on a bridge"]


lb = LocalBlend(prompts, ("car", ("cabriolet", "car")))
controller = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "car": .2},
                             self_replace_steps=.2, local_blend=lb)

_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

"""result with more attetnion to `"cabriolet"`"""

prompts = ["A car on a bridge",
           "A cabriolet car on a bridge"]


lb = LocalBlend(prompts, ("car", ("cabriolet", "car")))
controller_a = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "car": .2}, self_replace_steps=.2, local_blend=lb)

## pay 4 times more attention to the word "cabriolet"
equalizer = get_equalizer(prompts[1], ("cabriolet"), (4,))
controller = AttentionReweight(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "car": .2},
                               self_replace_steps=.2, equalizer=equalizer, local_blend=lb, controller=controller_a)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

