# -*- coding: utf-8 -*-
"""prompt-to-prompt_ldm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qOZyGFWwhCes_iAS6mISlN9TKFD2ux5F

## Copyright 2022 Google LLC. Double-click for license information.
"""

from google.colab import drive
drive.mount('/content/drive')

# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

!sudo apt-get install python3.9
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
!sudo update-alternatives --config python3

!python --version

!sudo apt-get update
!sudo apt-get install -y python3.9-distutils
!curl -O https://bootstrap.pypa.io/get-pip.py
!python3.9 get-pip.py

"""## Prompt-to-Prompt with Latent Diffusion"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/cmu/genai/GenAI-soft-prompt-to-prompt

!pip install -r requirements.txt

"""## Imports, constants, loading model"""

from typing import Union, Tuple, List, Callable, Dict, Optional
import torch
import torch.nn.functional as nnf
from diffusers import DiffusionPipeline
import numpy as np
from IPython.display import display
from PIL import Image
import abc
import ptp_utils
import seq_aligner

device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu')
model_id = "CompVis/ldm-text2im-large-256"
NUM_DIFFUSION_STEPS = 50
GUIDANCE_SCALE = 5.
MAX_NUM_WORDS = 77
# load model and scheduler
ldm = DiffusionPipeline.from_pretrained(model_id).to(device)
tokenizer = ldm.tokenizer

"""## Prompt-to-Prompt Attnetion Controllers
Our main logic is implemented in the `forward` call in an `AttentionControl` object.
The forward is called in each attention layer of the diffusion model and it can modify the input attnetion weights `attn`.

`is_cross`, `place_in_unet in ("down", "mid", "up")`, `AttentionControl.cur_step` can help us track the exact attention layer and timestamp during the diffusion iference.

"""

class LocalBlend:

    def __call__(self, x_t, attention_store, step):
        k = 1
        maps = attention_store["down_cross"][:2] + attention_store["up_cross"][3:6]
        maps = [item.reshape(self.alpha_layers.shape[0], -1, 1, 16, 16, MAX_NUM_WORDS) for item in maps]
        maps = torch.cat(maps, dim=1)
        maps = (maps * self.alpha_layers).sum(-1).mean(1)
        mask = nnf.max_pool2d(maps, (k * 2 + 1, k * 2 +1), (1, 1), padding=(k, k))
        mask = nnf.interpolate(maps, size=(x_t.shape[2:]))
        mask = mask / mask.max(2, keepdims=True)[0].max(3, keepdims=True)[0]
        mask = mask.gt(self.threshold)
        mask = (mask[:1] + mask).float()
        x_t = x_t[:1] + mask * (x_t - x_t[:1])
        return x_t

    def __init__(self, prompts: List[str], words: [List[List[str]]], threshold: float = .3):
        alpha_layers = torch.zeros(len(prompts),  1, 1, 1, 1, MAX_NUM_WORDS)
        for i, (prompt, words_) in enumerate(zip(prompts, words)):
            if type(words_) is str:
                words_ = [words_]
            for word in words_:
                ind = ptp_utils.get_word_inds(prompt, word, tokenizer)
                alpha_layers[i, :, :, :, :, ind] = 1
        self.alpha_layers = alpha_layers.to(device)
        self.threshold = threshold


class AttentionControl(abc.ABC):

    def step_callback(self, x_t):
        return x_t

    def between_steps(self):
        return

    @abc.abstractmethod
    def forward (self, attn, is_cross: bool, place_in_unet: str):
        raise NotImplementedError

    def __call__(self, attn, is_cross: bool, place_in_unet: str):
        h = attn.shape[0]
        attn[h // 2:] = self.forward(attn[h // 2:], is_cross, place_in_unet)
        self.cur_att_layer += 1
        if self.cur_att_layer == self.num_att_layers:
            self.cur_att_layer = 0
            self.cur_step += 1
            self.between_steps()
        return attn

    def reset(self):
        self.cur_step = 0
        self.cur_att_layer = 0

    def __init__(self):
        self.cur_step = 0
        self.num_att_layers = -1
        self.cur_att_layer = 0


class EmptyControl(AttentionControl):

    def forward (self, attn, is_cross: bool, place_in_unet: str):
        return attn


class AttentionStore(AttentionControl):

    @staticmethod
    def get_empty_store():
        return {"down_cross": [], "mid_cross": [], "up_cross": [],
                "down_self": [],  "mid_self": [],  "up_self": []}

    def forward(self, attn, is_cross: bool, place_in_unet: str):
        if attn.shape[1] <= 16 ** 2:  # avoid memory overhead
            key = f"{place_in_unet}_{'cross' if is_cross else 'self'}"
            self.step_store[key].append(attn)
        return attn

    def between_steps(self):
        if len(self.attention_store) == 0:
            self.attention_store = self.step_store
        else:
            for key in self.attention_store:
                for i in range(len(self.attention_store[key])):
                    self.attention_store[key][i] += self.step_store[key][i]
        self.step_store = self.get_empty_store()

    def get_average_attention(self):
        average_attention = {key: [item / self.cur_step for item in self.attention_store[key]] for key in self.attention_store}
        return average_attention


    def reset(self):
        super(AttentionStore, self).reset()
        self.step_store = self.get_empty_store()
        self.attention_store = {}

    def __init__(self):
        super(AttentionStore, self).__init__()
        self.step_store = self.get_empty_store()
        self.attention_store = {}


class AttentionControlEdit(AttentionStore, abc.ABC):

    def step_callback(self, x_t):
        if self.local_blend is not None:
            x_t = self.local_blend(x_t, self.attention_store, self.cur_step)
        return x_t

    def replace_self_attention(self, attn_base, att_replace):
        if att_replace.shape[2] <= 16 ** 2:
            return attn_base.unsqueeze(0).expand(att_replace.shape[0], *attn_base.shape)
        else:
            return att_replace

    @abc.abstractmethod
    def replace_cross_attention(self, attn_base, att_replace):
        raise NotImplementedError

    def forward(self, attn, is_cross: bool, place_in_unet: str):
        super(AttentionControlEdit, self).forward(attn, is_cross, place_in_unet)
        if is_cross or (self.num_self_replace[0] <= self.cur_step < self.num_self_replace[1]):
            h = attn.shape[0] // (self.batch_size)
            attn = attn.reshape(self.batch_size, h, *attn.shape[1:])
            attn_base, attn_repalce = attn[0], attn[1:]
            if is_cross:
                alpha_words = self.cross_replace_alpha[self.cur_step]
                attn_repalce_new = self.replace_cross_attention(attn_base, attn_repalce) * alpha_words + (1 - alpha_words) * attn_repalce
                attn[1:] = attn_repalce_new
            else:
                attn[1:] = self.replace_self_attention(attn_base, attn_repalce)
            attn = attn.reshape(self.batch_size * h, *attn.shape[2:])
        return attn

    def __init__(self, prompts, num_steps: int,
                 cross_replace_steps: Union[float, Tuple[float, float], Dict[str, Tuple[float, float]]],
                 self_replace_steps: Union[float, Tuple[float, float]],
                 local_blend: Optional[LocalBlend],
                 time_step_scaler=None
                 ):
        super(AttentionControlEdit, self).__init__()
        self.batch_size = len(prompts)
        self.cross_replace_alpha = ptp_utils.get_time_words_attention_alpha(
            prompts,
            num_steps,
            cross_replace_steps,
            tokenizer,
            time_step_scaler=time_step_scaler
        ).to(device)
        if type(self_replace_steps) is float:
            self_replace_steps = 0, self_replace_steps
        self.num_self_replace = int(num_steps * self_replace_steps[0]), int(num_steps * self_replace_steps[1])
        self.local_blend = local_blend

class AttentionReplace(AttentionControlEdit):

    def replace_cross_attention(self, attn_base, att_replace):
        return torch.einsum('hpw,bwn->bhpn', attn_base, self.mapper)

    def __init__(self, prompts, num_steps: int, cross_replace_steps: float, self_replace_steps: float,
                 local_blend: Optional[LocalBlend] = None,
                 time_step_scaler=None):
        super(AttentionReplace, self).__init__(
            prompts, num_steps, cross_replace_steps, self_replace_steps, local_blend,
            time_step_scaler=time_step_scaler
        )
        self.mapper = seq_aligner.get_replacement_mapper(prompts, tokenizer).to(device)


class AttentionRefine(AttentionControlEdit):

    def replace_cross_attention(self, attn_base, att_replace):
        attn_base_replace = attn_base[:, :, self.mapper].permute(2, 0, 1, 3)
        attn_replace = attn_base_replace * self.alphas + att_replace * (1 - self.alphas)
        return attn_replace

    def __init__(self, prompts, num_steps: int, cross_replace_steps: float, self_replace_steps: float,
                 local_blend: Optional[LocalBlend] = None,
                 time_step_scaler=None):
        super(AttentionRefine, self).__init__(
            prompts, num_steps, cross_replace_steps, self_replace_steps, local_blend,
            time_step_scaler=time_step_scaler
        )
        self.mapper, alphas = seq_aligner.get_refinement_mapper(prompts, tokenizer)
        self.mapper, alphas = self.mapper.to(device), alphas.to(device)
        self.alphas = alphas.reshape(alphas.shape[0], 1, 1, alphas.shape[1])


class AttentionReweight(AttentionControlEdit):

    def replace_cross_attention(self, attn_base, att_replace):
        if self.prev_controller is not None:
            attn_base = self.prev_controller.replace_cross_attention(attn_base, att_replace)
        attn_replace = attn_base[None, :, :, :] * self.equalizer[:, None, None, :]
        return attn_replace

    def __init__(self, prompts, num_steps: int, cross_replace_steps: float, self_replace_steps: float, equalizer,
                local_blend: Optional[LocalBlend] = None,
                controller: Optional[AttentionControlEdit] = None,
                time_step_scaler=None):
        super(AttentionReweight, self).__init__(
            prompts, num_steps, cross_replace_steps, self_replace_steps, local_blend,
            time_step_scaler=time_step_scaler
        )
        self.equalizer = equalizer.to(device)
        self.prev_controller = controller


def get_equalizer(text: str, word_select: Union[int, Tuple[int, ...]], values: Union[List[float],
                  Tuple[float, ...]]):
    if type(word_select) is int or type(word_select) is str:
        word_select = (word_select,)
    equalizer = torch.ones(len(values), 77)
    values = torch.tensor(values, dtype=torch.float32)
    for word in word_select:
        inds = ptp_utils.get_word_inds(text, word, tokenizer)
        for i in inds:
            equalizer[:, i] = values
    return equalizer

def aggregate_attention(attention_store: AttentionStore, res: int, from_where: List[str], is_cross: bool, select: int):
    out = []
    attention_maps = attention_store.get_average_attention()
    num_pixels = res ** 2
    for location in from_where:
        for item in attention_maps[f"{location}_{'cross' if is_cross else 'self'}"]:
            if item.shape[1] == num_pixels:
                cross_maps = item.reshape(len(prompts), -1, res, res, item.shape[-1])[select]
                out.append(cross_maps)
    out = torch.cat(out, dim=0)
    out = out.sum(0) / out.shape[0]
    return out.cpu()


def show_cross_attention(attention_store: AttentionStore, res: int, from_where: List[str], select: int = 0):
    tokens = tokenizer.encode(prompts[select])
    decoder = tokenizer.decode
    attention_maps = aggregate_attention(attention_store, res, from_where, True, select)
    images = []
    for i in range(len(tokens)):
        image = attention_maps[:, :, i]
        image = 255 * image / image.max()
        image = image.unsqueeze(-1).expand(*image.shape, 3)
        image = image.numpy().astype(np.uint8)
        image = np.array(Image.fromarray(image).resize((256, 256)))
        image = ptp_utils.text_under_image(image, decoder(int(tokens[i])))
        images.append(image)
    ptp_utils.view_images(np.stack(images, axis=0))


def show_self_attention_comp(attention_store: AttentionStore, res: int, from_where: List[str],
                        max_com=10, select: int = 0):
    attention_maps = aggregate_attention(attention_store, res, from_where, False, select).numpy().reshape((res ** 2, res ** 2))
    u, s, vh = np.linalg.svd(attention_maps - np.mean(attention_maps, axis=1, keepdims=True))
    images = []
    for i in range(max_com):
        image = vh[i].reshape(res, res)
        image = image - image.min()
        image = 255 * image / image.max()
        image = np.repeat(np.expand_dims(image, axis=2), 3, axis=2).astype(np.uint8)
        image = Image.fromarray(image).resize((256, 256))
        image = np.array(image)
        images.append(image)
    ptp_utils.view_images(np.concatenate(images, axis=1))

def sort_by_eq(eq):

    def inner_(images):
        swap = 0
        if eq[-1] < 1:
            for i in range(len(eq)):
                if eq[i] > 1 and eq[i + 1] < 1:
                    swap = i + 2
                    break
        else:
             for i in range(len(eq)):
                if eq[i] < 1 and eq[i + 1] > 1:
                    swap = i + 2
                    break
        print(swap)
        if swap > 0:
            images = np.concatenate([images[1:swap], images[:1], images[swap:]], axis=0)

        return images
    return inner_


def run_and_display(prompts, controller, latent=None, run_baseline=True, callback:Optional[Callable[[np.ndarray], np.ndarray]] = None, generator=None):
    if run_baseline:
        print("w.o. prompt-to-prompt")
        images, latent = run_and_display(prompts, EmptyControl(), latent=latent, run_baseline=False)
        print("results with prompt-to-prompt")
    images, x_t = ptp_utils.text2image_ldm(ldm, prompts, controller, latent=latent, num_inference_steps=NUM_DIFFUSION_STEPS, guidance_scale=GUIDANCE_SCALE, generator=generator)
    if callback is not None:
        images = callback(images)
    ptp_utils.view_images(images)
    return images, x_t

"""## Cross-Attention Visualization"""

import os
import csv
import re
from typing import List, Tuple

RESULTS_ROOT = "results_new"
DATA_CSV = "prompts.csv"

def slugify(text: str) -> str:
    text = text.strip()
    text = re.sub(r"[^a-zA-Z0-9_-]+", "_", text)
    return text or "unknown"

def load_prompt_rows(csv_path: str) -> List[Tuple[str, List[str]]]:
    rows: List[Tuple[str, List[str]]] = []
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        first = True
        for line in reader:
            if first:
                first = False
                continue
            if not line:
                continue
            prompt_type = line[0].strip()
            prompts = [p.strip() for p in line[1:] if p.strip()]
            if not prompts:
                continue
            rows.append((prompt_type, prompts))
    return rows


def save_images_per_prompt(
    images: np.ndarray,
    experiment_name: str,
    prompt_type: str,
    out_root: str = RESULTS_ROOT,
):
    if images.ndim == 3:
        images = images[None, ...]

    type_dir = os.path.join(out_root, experiment_name, slugify(prompt_type))
    os.makedirs(type_dir, exist_ok=True)

    for idx, img in enumerate(images):
        pil_img = Image.fromarray(img.astype(np.uint8))
        out_path = os.path.join(type_dir, f"{idx}.png")
        pil_img.save(out_path)
        print(f"Saved: {out_path}")

# 6 experiments
import math
base_generator = torch.Generator().manual_seed(888)
num_steps = NUM_DIFFUSION_STEPS

def linear_decay_scaler(t: int):
    return 1.0 - float(t) / float(num_steps)

def sigmoid_decay_scaler(t, k=10):
    x = t / num_steps
    return 1.0 / (1.0 + math.exp(k * (x - 0.5)))

def quadratic_slow_to_fast_scaler(t: int, power: float = 2.0):
    """
    Concave-down decay like the black curve:
    starts near 1, decreases slowly at first,
    then drops quickly near the end.
    """
    x = float(t) / float(num_steps)
    alpha = 1.0 - (x ** power)
    return float(np.clip(alpha, 0.0, 1.0))

def exp_decay_scaler(t: int, tau: float = 0.3):
    """Exponential: starts near 1, decays quickly then slowly."""
    x = float(t) / float(num_steps)
    return float(np.exp(-x / tau))

def run_no_prompt_to_prompt(
    prompts: List[str],
    prompt_type: str,
    generator: torch.Generator = None,
):
    controller = EmptyControl()
    images, latent = run_and_display(
        prompts,
        controller,
        latent=None,
        run_baseline=False,
        generator=generator,
    )
    save_images_per_prompt(images, "no_prompt_to_prompt", prompt_type)
    return latent

def run_p2p_experiment(
    prompts: List[str],
    prompt_type: str,
    experiment_name: str,
    time_step_scaler,
    latent,
    cross_replace_steps: float = 1.0,
):
    controller = AttentionReplace(
        prompts=prompts,
        num_steps=NUM_DIFFUSION_STEPS,
        cross_replace_steps=cross_replace_steps,
        self_replace_steps=0.5,
        local_blend=None,
        time_step_scaler=time_step_scaler,
    )
    images, _ = run_and_display(
        prompts,
        controller,
        latent=latent,
        run_baseline=False,
    )
    save_images_per_prompt(images, experiment_name, prompt_type)

def run_all_experiments_for_row(
    prompt_type: str,
    prompts: List[str],
    base_seed: int = 888,
):

    print(f"\n=== Type: {prompt_type} ===")
    print("Prompts:", prompts)

    g = torch.Generator().manual_seed(base_seed)

    # 1) no prompt-to-prompt
    print("[1/6] Running: no_prompt_to_prompt")
    latent = run_no_prompt_to_prompt(prompts, prompt_type, generator=g)

    # 2) exp
    print("[2/6] Running: exp")
    run_p2p_experiment(
        prompts,
        prompt_type,
        experiment_name="exp",
        time_step_scaler=exp_decay_scaler,
        latent=latent,
    )

    # 3) linear
    print("[3/6] Running: linear")
    run_p2p_experiment(
        prompts,
        prompt_type,
        experiment_name="linear",
        time_step_scaler=linear_decay_scaler,
        latent=latent,
    )

    # 4) quadratic
    print("[4/6] Running: quadratic")
    run_p2p_experiment(
        prompts,
        prompt_type,
        experiment_name="quadratic",
        time_step_scaler=quadratic_slow_to_fast_scaler,
        latent=latent,
    )

    # 5) replace
    print("[5/6] Running: replace")
    run_p2p_experiment(
        prompts,
        prompt_type,
        experiment_name="replace",
        time_step_scaler=None,
        latent=latent,
        cross_replace_steps=.5,
    )

    # 6) sigmoid
    print("[6/6] Running: sigmoid")
    run_p2p_experiment(
        prompts,
        prompt_type,
        experiment_name="sigmoid",
        time_step_scaler=sigmoid_decay_scaler,
        latent=latent,
    )

    print(f"=== Done type: {prompt_type} ===")

rows = load_prompt_rows(DATA_CSV)

print(f"Loaded {len(rows)} rows from {DATA_CSV}")

for row_idx, (prompt_type, prompts) in enumerate(rows):
    run_all_experiments_for_row(
        prompt_type=prompt_type,
        prompts=prompts,
        base_seed=888,
    )

print("All experiments finished.")

old_prompt = "A bear holding a blue balloon."
new_prompt = "A bear holding a red balloon."

target_token = "red"

import math
import numpy as np
from PIL import Image

def exp_decay_scaler(t: int, tau: float = 0.3) -> float:
    x = float(t) / float(NUM_DIFFUSION_STEPS)
    return float(np.exp(-x / tau))

def linear_decay_scaler(t: int) -> float:
    x = float(t) / float(NUM_DIFFUSION_STEPS)
    return float(np.clip(1.0 - x, 0.0, 1.0))

def quadratic_slow_to_fast_scaler(t: int, power: float = 2.0) -> float:
    x = float(t) / float(NUM_DIFFUSION_STEPS)
    alpha = 1.0 - (x ** power)
    return float(np.clip(alpha, 0.0, 1.0))

def sigmoid_decay_scaler(t: int, k: float = 10.0) -> float:
    x = float(t) / float(NUM_DIFFUSION_STEPS)
    return float(1.0 / (1.0 + math.exp(k * (x - 0.5))))

class StepAttentionStore(AttentionStore):

    def __init__(self):
        super().__init__()
        self.step_history = []

    def reset(self):
        super().reset()
        self.step_history = []

    def between_steps(self):
        self.step_history.append({
            k: [v.clone() for v in vs]
            for k, vs in self.step_store.items()
        })
        super().between_steps()


class StepAttentionReplace(AttentionReplace):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.step_history = []

    def reset(self):
        super().reset()
        self.step_history = []

    def between_steps(self):
        self.step_history.append({
            k: [v.clone() for v in self.step_store[k]]
            for k in self.step_store
        })
        super().between_steps()

def aggregate_attention_for_step(
    step_store: dict,
    res: int,
    from_where,
    is_cross: bool,
    select: int,
    num_prompts: int,
):
    out = []
    num_pixels = res ** 2
    for location in from_where:
        key = f"{location}_{'cross' if is_cross else 'self'}"
        if key not in step_store:
            continue
        for item in step_store[key]:
            if item.shape[1] == num_pixels:
                cross_maps = item.reshape(num_prompts, -1, res, res, item.shape[-1])[select]
                out.append(cross_maps)
    if not out:
        return None
    out = torch.cat(out, dim=0)
    out = out.sum(0) / out.shape[0]
    return out.cpu()


def plot_token_cross_attention_over_time(
    controller_with_history,
    experiment_name: str,
    prompts_pair,
    token_index: int,
    res: int = 16,
    from_where = ("down", "mid", "up"),
    prompt_index: int = 1,
    step_stride: int = 5,
):
    num_prompts = len(prompts_pair)
    images = []

    for step, step_store in enumerate(controller_with_history.step_history):
        if step % step_stride != 0:
            continue

        attn_map = aggregate_attention_for_step(
            step_store,
            res=res,
            from_where=from_where,
            is_cross=True,
            select=prompt_index,
            num_prompts=num_prompts,
        )
        if attn_map is None:
            continue

        token_map = attn_map[:, :, token_index]
        token_map = token_map.numpy()
        token_map = token_map - token_map.min()
        if token_map.max() > 0:
            token_map = token_map / token_map.max()
        token_map = (255 * token_map).astype(np.uint8)
        token_map_rgb = np.stack([token_map]*3, axis=-1)

        pil_img = Image.fromarray(token_map_rgb).resize((256, 256))
        img = np.array(pil_img)

        img = ptp_utils.text_under_image(img, f"{experiment_name} | step {step}")
        images.append(img)

    if images:
        print(f"[{experiment_name}] token attention over time")
        ptp_utils.view_images(np.stack(images, axis=0))
    else:
        print(f"[{experiment_name}] No attention maps collected.")


def resolve_target_token_index(new_prompt: str, target_token):
    if isinstance(target_token, int):
        return target_token

    inds = ptp_utils.get_word_inds(new_prompt, target_token, tokenizer)
    if len(inds) == 0:
        raise ValueError(f"could'n find word {target_token} in new prompt.")
    return inds[0]

token_index = resolve_target_token_index(new_prompt, target_token)
print(f"Using token index: {token_index} for target '{target_token}' in new_prompt.")


prompts_pair = [old_prompt, new_prompt]
print("Prompts:", prompts_pair)

generator = torch.Generator().manual_seed(888)

print("\n[1/6] no_prompt_to_prompt")
controller_no = StepAttentionStore()
images_no, latent = run_and_display(
    prompts_pair,
    controller_no,
    latent=None,
    run_baseline=False,
    generator=generator,
)
plot_token_cross_attention_over_time(
    controller_no,
    experiment_name="no_prompt_to_prompt",
    prompts_pair=prompts_pair,
    token_index=token_index,
)

def run_p2p_with_scaler(name, scaler_fn, cross_replace_steps: float = 1.0):
    print(f"\nRunning [{name}]  (cross_replace_steps={cross_replace_steps})")
    controller = StepAttentionReplace(
        prompts=prompts_pair,
        num_steps=NUM_DIFFUSION_STEPS,
        cross_replace_steps=cross_replace_steps,
        self_replace_steps=0.5,
        local_blend=None,
        time_step_scaler=scaler_fn,
    )
    images, _ = run_and_display(
        prompts_pair,
        controller,
        latent=latent,
        run_baseline=False,
    )
    plot_token_cross_attention_over_time(
        controller,
        experiment_name=name,
        prompts_pair=prompts_pair,
        token_index=token_index,
    )

print("\n[2/6] exp")
run_p2p_with_scaler("exp", exp_decay_scaler)

print("\n[3/6] linear")
run_p2p_with_scaler("linear", linear_decay_scaler)

print("\n[4/6] quadratic")
run_p2p_with_scaler("quadratic", quadratic_slow_to_fast_scaler)

print("\n[5/6] replace")
run_p2p_with_scaler("replace", None, cross_replace_steps=0.5)

print("\n[6/6] sigmoid")
run_p2p_with_scaler("sigmoid", sigmoid_decay_scaler)

print("\nAll 6 experiments finished.")

g_cpu = torch.Generator().manual_seed(888)
prompts = ["A painting of a bear eating an apple"]
controller = AttentionStore()
images, x_t = run_and_display(prompts, controller, run_baseline=False, generator=g_cpu)
show_cross_attention(controller, res=16, from_where=["up", "down"])

"""## Replacement edit with Prompt-to-Prompt"""

import importlib
importlib.reload(ptp_utils)

prompts = ["A painting of a bear eating an apple",
           "A painting of a cat eating an apple",
           "A painting of a dog eating an apple",
           "A painting of a lion eating an apple",
          ]

num_steps = NUM_DIFFUSION_STEPS

#hard to soft
def linear_decay_scaler(t: int):
    return 1.0 - float(t) / float(num_steps)

controller = AttentionReplace(
    prompts,
    NUM_DIFFUSION_STEPS,
    cross_replace_steps=1.0,
    self_replace_steps=0.2,
    local_blend=None,
    time_step_scaler=linear_decay_scaler
)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)

from ptp_utils import plot_alpha_for_word

plot_alpha_for_word(
    prompts=prompts,
    alpha_time_words=controller.cross_replace_alpha,
    tokenizer=tokenizer,
    word="cat",
    prompt_index=1
)

import math

num_steps = NUM_DIFFUSION_STEPS

def sigmoid_decay_scaler(t, k=10):
    x = t / num_steps
    return 1.0 / (1.0 + math.exp(k * (x - 0.5)))

prompts = ["A painting of a bear eating an apple",
           "A painting of a cat eating an apple",
           "A painting of a dog eating an apple",
           "A painting of a lion eating an apple",
          ]


controller = AttentionReplace(
    prompts,
    NUM_DIFFUSION_STEPS,
    cross_replace_steps=1.0,
    self_replace_steps=0.2,
    local_blend=None,
    time_step_scaler=sigmoid_decay_scaler
)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)

from ptp_utils import plot_alpha_for_word

plot_alpha_for_word(
    prompts=prompts,
    alpha_time_words=controller.cross_replace_alpha,
    tokenizer=tokenizer,
    word="cat",
    prompt_index=1
)

import math

num_steps = NUM_DIFFUSION_STEPS

def quadratic_slow_to_fast_scaler(t: int, power: float = 2.0):
    """
    Concave-down decay like the black curve:
    starts near 1, decreases slowly at first,
    then drops quickly near the end.
    """
    x = float(t) / float(num_steps)   # x in [0, 1]
    alpha = 1.0 - (x ** power)        # 1 - x^2 (or x^p)
    return float(np.clip(alpha, 0.0, 1.0))

prompts = ["A painting of a bear eating an apple",
           "A painting of a cat eating an apple",
           "A painting of a dog eating an apple",
           "A painting of a lion eating an apple",
          ]


controller = AttentionReplace(
    prompts,
    NUM_DIFFUSION_STEPS,
    cross_replace_steps=1.0,
    self_replace_steps=0.2,
    local_blend=None,
    time_step_scaler=quadratic_slow_to_fast_scaler
)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)

from ptp_utils import plot_alpha_for_word

plot_alpha_for_word(
    prompts=prompts,
    alpha_time_words=controller.cross_replace_alpha,
    tokenizer=tokenizer,
    word="cat",
    prompt_index=1
)

import math

num_steps = NUM_DIFFUSION_STEPS

def exp_decay_scaler(t: int, tau: float = 0.3):
    """Exponential: starts near 1, decays quickly then slowly."""
    x = float(t) / float(num_steps)
    return float(np.exp(-x / tau))

prompts = ["A painting of a bear eating an apple",
           "A painting of a cat eating an apple",
           "A painting of a dog eating an apple",
           "A painting of a lion eating an apple",
          ]


controller = AttentionReplace(
    prompts,
    NUM_DIFFUSION_STEPS,
    cross_replace_steps=1.0,
    self_replace_steps=0.2,
    local_blend=None,
    time_step_scaler=exp_decay_scaler
)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)

from ptp_utils import plot_alpha_for_word

plot_alpha_for_word(
    prompts=prompts,
    alpha_time_words=controller.cross_replace_alpha,
    tokenizer=tokenizer,
    word="cat",
    prompt_index=1
)

prompts = ["A painting of a bear eating an apple",
           "A painting of a cat eating an apple",
           "A painting of a dog eating an apple",
           "A painting of a lion eating an apple",
          ]
controller = AttentionReplace(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=.8, self_replace_steps=.2)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)


from ptp_utils import plot_alpha_for_word

plot_alpha_for_word(
    prompts=prompts,
    alpha_time_words=controller.cross_replace_alpha,
    tokenizer=tokenizer,
    word="cat",
    prompt_index=1
)

"""### Modify Cross-Attention injection #steps for specific words
Next, we can reduce the restriction on our lion by reducing the number of cross-attention injection with respect to the replacement words.
"""

prompts = ["A painting of a squirrel eating a burger",
           "A painting of a lion eating a burger",
           "A painting of a cat eating a burger",
           "A painting of a deer eating a burger",
          ]
controller = AttentionReplace(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "lion": .4, "cat": .3, "deer": .2},
                              self_replace_steps=0.2)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

"""### Local Edit
Lastly, if we want to only replace the burger, we can apply a local edit with respect to to the replacement words.
"""

prompts = ["A painting of a bear eating an apple",
           "A painting of a cat eating an apple",
           "A painting of a dog eating an apple",
           "A painting of a lion eating an apple",
          ]

controller = AttentionReplace(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "cat": .2, "dog": .2, "lion": .2},
                              self_replace_steps=0.2, local_blend=None)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

prompts = ["A painting of a squirrel eating a burger",
           "A painting of a squirrel eating a lasagne",
           "A painting of a squirrel eating a pretzel",
           "A painting of a squirrel eating a sushi",
          ]

lb = LocalBlend(prompts, ("burger", "lasagne", "pretzel", "sushi"))
controller = AttentionReplace(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "lasagne": .2, "pretzel": .2, "sushi": .2},
                              self_replace_steps=0.2, local_blend=lb)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

"""## Refinement edit"""

prompts = ["A painting of a squirrel eating a burger",
           "A watercolor painting of a squirrel eating a burger",
           "A dark painting of a squirrel eating a burger",
           "A realitic photo of a squirrel eating a burger",
          ]

controller = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=.8, self_replace_steps=.2)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)

prompts = ["A river between mountains",
           "A river between mountains at autumn",
           "A river between mountains at winter",
           "A river between mountains at sunset",
          ]

controller = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=.8, self_replace_steps=.4)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)

prompts = ["A car on a bridge",
           "A muscle car on a bridge",
           "A futuristic car on a bridge",
           "A retro car on a bridge",]


lb = LocalBlend(prompts, ("car", ("muscle", "car"), ("futuristic", "car"), ("retro", "car")))
controller = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "car": .2},
                             self_replace_steps=.4, local_blend=lb)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=True)

"""## Attention Re-Weighting"""

prompts = ["A photo of a sunset by the sea"] * 4
equalizer = get_equalizer(prompts[0], word_select=("sunset",), values=(.5, .0, -.5))
controller = AttentionReweight(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=1., self_replace_steps=.2, equalizer=equalizer)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

prompts = ["A photo of a poppy field at night"] * 4
equalizer = get_equalizer(prompts[0], word_select=("night",), values=(.5, 0,  -.5))
controller = AttentionReweight(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=1., self_replace_steps=.2, equalizer=equalizer)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

"""### Edit Composition
It might be useful to use Attention Re-Weighting with a previous edit method.
"""

prompts = ["cake",
           "birthday cake"]


lb = LocalBlend(prompts, ("cake", ("birthday", "cake")))
controller = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=.8, self_replace_steps=.4, local_blend=lb)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

"""result with more attetnion to `"birthday"`"""

prompts = ["cake",
           "birthday cake"]


lb = LocalBlend(prompts, ("cake", ("birthday", "cake")))
controller_a = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=.8, self_replace_steps=.4, local_blend=lb)

## pay 5 times more attention to the word "birthday"
equalizer = get_equalizer(prompts[1], ("birthday"), (5,))
controller = AttentionReweight(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps=.8, self_replace_steps=.4, equalizer=equalizer, local_blend=lb, controller=controller_a)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

prompts = ["A car on a bridge",
           "A cabriolet car on a bridge"]


lb = LocalBlend(prompts, ("car", ("cabriolet", "car")))
controller = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "car": .2},
                             self_replace_steps=.2, local_blend=lb)

_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

"""result with more attetnion to `"cabriolet"`"""

prompts = ["A car on a bridge",
           "A cabriolet car on a bridge"]


lb = LocalBlend(prompts, ("car", ("cabriolet", "car")))
controller_a = AttentionRefine(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "car": .2}, self_replace_steps=.2, local_blend=lb)

## pay 4 times more attention to the word "cabriolet"
equalizer = get_equalizer(prompts[1], ("cabriolet"), (4,))
controller = AttentionReweight(prompts, NUM_DIFFUSION_STEPS, cross_replace_steps={"default_": 1., "car": .2},
                               self_replace_steps=.2, equalizer=equalizer, local_blend=lb, controller=controller_a)
_ = run_and_display(prompts, controller, latent=x_t, run_baseline=False)

